export type TipoImpacto = 'risco' | 'oportunidade' | 'informativo';
export type TributoAfetado = 'INSS_PATRONAL' | 'INSS_SEGURADO' | 'INSS_RAT' | 'INSS_TERCEIROS' | 'FGTS' | 'IRRF' | 'CSLL' | 'MULTIPLO';
export type StatusAnalise = 'pendente' | 'em_analise' | 'confirmado' | 'descartado' | 'justificado';

export interface Database {
  public: {
    Tables: {
      empresas: {
        Row: {
          id: string;
          user_id: string;
          cnpj: string;
          razao_social: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          cnpj: string;
          razao_social: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          cnpj?: string;
          razao_social?: string;
          created_at?: string;
        };
      };
      rubricas: {
        Row: {
          id: string;
          empresa_id: string;
          codigo: string;
          descricao: string;
          natureza: string;
          tipo: string | null;
          incid_inss: string;
          incid_irrf: string;
          incid_fgts: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          codigo: string;
          descricao: string;
          natureza?: string;
          tipo?: string | null;
          incid_inss?: string;
          incid_irrf?: string;
          incid_fgts?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          codigo?: string;
          descricao?: string;
          natureza?: string;
          tipo?: string | null;
          incid_inss?: string;
          incid_irrf?: string;
          incid_fgts?: string;
          created_at?: string;
        };
      };
      colaboradores: {
        Row: {
          id: string;
          empresa_id: string;
          cpf: string;
          nome: string;
          matricula: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          cpf: string;
          nome: string;
          matricula?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          cpf?: string;
          nome?: string;
          matricula?: string | null;
          created_at?: string;
        };
      };
      importacoes: {
        Row: {
          id: string;
          empresa_id: string;
          tipo_evento: string;
          nome_arquivo: string;
          competencia: string | null;
          status: string;
          registros_processados: number;
          erros: unknown[];
          arquivo_origem_zip: string | null;
          caminho_no_zip: string | null;
          tabela_destino: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          tipo_evento: string;
          nome_arquivo: string;
          competencia?: string | null;
          status?: string;
          registros_processados?: number;
          erros?: unknown[];
          arquivo_origem_zip?: string | null;
          caminho_no_zip?: string | null;
          tabela_destino?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          tipo_evento?: string;
          nome_arquivo?: string;
          competencia?: string | null;
          status?: string;
          registros_processados?: number;
          erros?: unknown[];
          arquivo_origem_zip?: string | null;
          caminho_no_zip?: string | null;
          tabela_destino?: string | null;
          created_at?: string;
        };
      };
      remuneracoes: {
        Row: {
          id: string;
          empresa_id: string;
          colaborador_id: string;
          importacao_id: string | null;
          competencia: string;
          valor_bruto: number;
          valor_descontos: number;
          valor_liquido: number;
          base_inss: number;
          base_irrf: number;
          base_fgts: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          colaborador_id: string;
          importacao_id?: string | null;
          competencia: string;
          valor_bruto?: number;
          valor_descontos?: number;
          valor_liquido?: number;
          base_inss?: number;
          base_irrf?: number;
          base_fgts?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          colaborador_id?: string;
          importacao_id?: string | null;
          competencia?: string;
          valor_bruto?: number;
          valor_descontos?: number;
          valor_liquido?: number;
          base_inss?: number;
          base_irrf?: number;
          base_fgts?: number;
          created_at?: string;
        };
      };
      itens_remuneracao: {
        Row: {
          id: string;
          remuneracao_id: string;
          rubrica_id: string | null;
          codigo_rubrica: string;
          descricao: string | null;
          natureza: string;
          referencia: number;
          valor: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          remuneracao_id: string;
          rubrica_id?: string | null;
          codigo_rubrica: string;
          descricao?: string | null;
          natureza?: string;
          referencia?: number;
          valor?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          remuneracao_id?: string;
          rubrica_id?: string | null;
          codigo_rubrica?: string;
          descricao?: string | null;
          natureza?: string;
          referencia?: number;
          valor?: number;
          created_at?: string;
        };
      };
      divergencias: {
        Row: {
          id: string;
          empresa_id: string;
          remuneracao_id: string | null;
          item_remuneracao_id: string | null;
          tipo: string;
          tipo_impacto: TipoImpacto;
          tributo_afetado: TributoAfetado | null;
          natureza_rubrica: string | null;
          descricao: string;
          valor_original: number;
          valor_recalculado: number;
          diferenca: number;
          severidade: string;
          fundamento_legal: string | null;
          status_analise: StatusAnalise;
          competencia_inicio: string | null;
          competencia_fim: string | null;
          processo_vinculado: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          remuneracao_id?: string | null;
          item_remuneracao_id?: string | null;
          tipo: string;
          tipo_impacto?: TipoImpacto;
          tributo_afetado?: TributoAfetado | null;
          natureza_rubrica?: string | null;
          descricao: string;
          valor_original?: number;
          valor_recalculado?: number;
          diferenca?: number;
          severidade?: string;
          fundamento_legal?: string | null;
          status_analise?: StatusAnalise;
          competencia_inicio?: string | null;
          competencia_fim?: string | null;
          processo_vinculado?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          remuneracao_id?: string | null;
          item_remuneracao_id?: string | null;
          tipo?: string;
          tipo_impacto?: TipoImpacto;
          tributo_afetado?: TributoAfetado | null;
          natureza_rubrica?: string | null;
          descricao?: string;
          valor_original?: number;
          valor_recalculado?: number;
          diferenca?: number;
          severidade?: string;
          fundamento_legal?: string | null;
          status_analise?: StatusAnalise;
          competencia_inicio?: string | null;
          competencia_fim?: string | null;
          processo_vinculado?: string | null;
          created_at?: string;
        };
      };
      apuracoes: {
        Row: {
          id: string;
          empresa_id: string;
          competencia: string;
          total_bruto_original: number;
          total_bruto_recalculado: number;
          total_inss_original: number;
          total_inss_recalculado: number;
          total_irrf_original: number;
          total_irrf_recalculado: number;
          total_fgts_original: number;
          total_fgts_recalculado: number;
          total_divergencias: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          competencia: string;
          total_bruto_original?: number;
          total_bruto_recalculado?: number;
          total_inss_original?: number;
          total_inss_recalculado?: number;
          total_irrf_original?: number;
          total_irrf_recalculado?: number;
          total_fgts_original?: number;
          total_fgts_recalculado?: number;
          total_divergencias?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          competencia?: string;
          total_bruto_original?: number;
          total_bruto_recalculado?: number;
          total_inss_original?: number;
          total_inss_recalculado?: number;
          total_irrf_original?: number;
          total_irrf_recalculado?: number;
          total_fgts_original?: number;
          total_fgts_recalculado?: number;
          total_divergencias?: number;
          created_at?: string;
        };
      };
      base_conhecimento_rubricas: {
        Row: {
          id: string;
          natureza_rubrica: string;
          descricao_padrao: string;
          incid_inss_padrao: string;
          incid_irrf_padrao: string;
          incid_fgts_padrao: string;
          fundamentacao_legal: string | null;
          observacoes: string | null;
          vigencia_inicio: string;
          vigencia_fim: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          natureza_rubrica: string;
          descricao_padrao: string;
          incid_inss_padrao?: string;
          incid_irrf_padrao?: string;
          incid_fgts_padrao?: string;
          fundamentacao_legal?: string | null;
          observacoes?: string | null;
          vigencia_inicio?: string;
          vigencia_fim?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          natureza_rubrica?: string;
          descricao_padrao?: string;
          incid_inss_padrao?: string;
          incid_irrf_padrao?: string;
          incid_fgts_padrao?: string;
          fundamentacao_legal?: string | null;
          observacoes?: string | null;
          vigencia_inicio?: string;
          vigencia_fim?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      evt_s1070: {
        Row: {
          id: string;
          empresa_id: string;
          id_evento: string | null;
          nr_processo: string;
          tp_proc: number;
          ind_suspensao: number | null;
          cod_susp: string | null;
          ind_decisao: string | null;
          tp_insc_estab: number | null;
          nr_insc_estab: string | null;
          uf_vara: string | null;
          tp_vara: number | null;
          ext_decisao: string | null;
          obs_processo: string | null;
          dt_inicio: string | null;
          dt_fim: string | null;
          ini_valid: string | null;
          fim_valid: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          id_evento?: string | null;
          nr_processo: string;
          tp_proc: number;
          ind_suspensao?: number | null;
          cod_susp?: string | null;
          ind_decisao?: string | null;
          tp_insc_estab?: number | null;
          nr_insc_estab?: string | null;
          uf_vara?: string | null;
          tp_vara?: number | null;
          ext_decisao?: string | null;
          obs_processo?: string | null;
          dt_inicio?: string | null;
          dt_fim?: string | null;
          ini_valid?: string | null;
          fim_valid?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          id_evento?: string | null;
          nr_processo?: string;
          tp_proc?: number;
          ind_suspensao?: number | null;
          cod_susp?: string | null;
          ind_decisao?: string | null;
          tp_insc_estab?: number | null;
          nr_insc_estab?: string | null;
          uf_vara?: string | null;
          tp_vara?: number | null;
          ext_decisao?: string | null;
          obs_processo?: string | null;
          dt_inicio?: string | null;
          dt_fim?: string | null;
          ini_valid?: string | null;
          fim_valid?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      dados_empresa_auditoria: {
        Row: {
          id: string;
          empresa_id: string;
          classificacao_tributaria: string;
          rat_original: number;
          fap: number;
          rat_ajustado: number;
          fpas: string | null;
          ind_desoneracao: boolean;
          ind_coop: number | null;
          ind_constr: number | null;
          ind_opt_reg_eletron: number | null;
          info_complementar: Record<string, unknown> | null;
          ini_valid: string | null;
          fim_valid: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          classificacao_tributaria: string;
          rat_original?: number;
          fap?: number;
          fpas?: string | null;
          ind_desoneracao?: boolean;
          ind_coop?: number | null;
          ind_constr?: number | null;
          ind_opt_reg_eletron?: number | null;
          info_complementar?: Record<string, unknown> | null;
          ini_valid?: string | null;
          fim_valid?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          classificacao_tributaria?: string;
          rat_original?: number;
          fap?: number;
          fpas?: string | null;
          ind_desoneracao?: boolean;
          ind_coop?: number | null;
          ind_constr?: number | null;
          ind_opt_reg_eletron?: number | null;
          info_complementar?: Record<string, unknown> | null;
          ini_valid?: string | null;
          fim_valid?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      rubrica_processo_vinculo: {
        Row: {
          id: string;
          empresa_id: string;
          rubrica_id: string;
          processo_id: string;
          tributo_suspenso: string;
          observacao: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          rubrica_id: string;
          processo_id: string;
          tributo_suspenso: string;
          observacao?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          rubrica_id?: string;
          processo_id?: string;
          tributo_suspenso?: string;
          observacao?: string | null;
          created_at?: string;
        };
      };
      entendimentos_tributacao: {
        Row: {
          id: string;
          codigo_rubrica: string;
          descricao_rubrica: string;
          incide_inss: boolean;
          incide_irrf: boolean;
          incide_fgts: boolean;
          observacoes: string | null;
          fundamento_legal: string | null;
          vigencia_inicio: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          codigo_rubrica: string;
          descricao_rubrica: string;
          incide_inss?: boolean;
          incide_irrf?: boolean;
          incide_fgts?: boolean;
          observacoes?: string | null;
          fundamento_legal?: string | null;
          vigencia_inicio?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          codigo_rubrica?: string;
          descricao_rubrica?: string;
          incide_inss?: boolean;
          incide_irrf?: boolean;
          incide_fgts?: boolean;
          observacoes?: string | null;
          fundamento_legal?: string | null;
          vigencia_inicio?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      evt_s1000: {
        Row: {
          id_evento: string;
          empresa_id: string;
          tp_insc: string;
          nr_insc: string;
          tipo_operacao: string;
          ini_valid: string;
          fim_valid: string | null;
          class_trib: string | null;
          ind_des_folha: string | null;
          ind_opt_reg_eletron: string | null;
          ind_porte: string | null;
          ind_coop: string | null;
          ind_constr: string | null;
          ind_opc_cp: string | null;
          cnpj_efr: string | null;
          isencao_nr_certif: string | null;
          isencao_dt_venc: string | null;
          data_importacao: string;
        };
        Insert: {
          id_evento: string;
          empresa_id: string;
          tp_insc: string;
          nr_insc: string;
          tipo_operacao: string;
          ini_valid: string;
          fim_valid?: string | null;
          class_trib?: string | null;
          ind_des_folha?: string | null;
          ind_opt_reg_eletron?: string | null;
          ind_porte?: string | null;
          ind_coop?: string | null;
          ind_constr?: string | null;
          ind_opc_cp?: string | null;
          cnpj_efr?: string | null;
          isencao_nr_certif?: string | null;
          isencao_dt_venc?: string | null;
          data_importacao?: string;
        };
        Update: {
          id_evento?: string;
          empresa_id?: string;
          tp_insc?: string;
          nr_insc?: string;
          tipo_operacao?: string;
          ini_valid?: string;
          fim_valid?: string | null;
          class_trib?: string | null;
          ind_des_folha?: string | null;
          ind_opt_reg_eletron?: string | null;
          ind_porte?: string | null;
          ind_coop?: string | null;
          ind_constr?: string | null;
          ind_opc_cp?: string | null;
          cnpj_efr?: string | null;
          isencao_nr_certif?: string | null;
          isencao_dt_venc?: string | null;
          data_importacao?: string;
        };
      };
      evt_s1010: {
        Row: {
          id: string;
          xml_version: string;
          xml_parsing_timestamp: string;
          usuario_id: string | null;
          empresa_id: string;
          xml_id: string;
          tp_amb: number | null;
          proc_emi: number | null;
          ver_proc: string | null;
          emp_tp_insc: number | null;
          emp_nr_insc: string | null;
          rub_operation_type: string | null;
          rub_cod_rubr: string | null;
          rub_ide_tab_rubr: string | null;
          rub_ini_valid: string | null;
          rub_fim_valid: string | null;
          rub_dsc_rubr: string | null;
          rub_nat_rubr: number | null;
          rub_tp_rubr: number | null;
          rub_cod_inc_cp: number | null;
          rub_cod_inc_irrf: number | null;
          rub_cod_inc_fgts: number | null;
          rub_cod_inc_sind: number | null;
          rec_tp_amb: number | null;
          rec_dh_recepcao: string | null;
          rec_versao_app_recepcao: string | null;
          rec_protocolo_envio: string | null;
          rec_cd_resposta: number | null;
          rec_desc_resposta: string | null;
          rec_dh_processamento: string | null;
          rec_nr_recibo: string | null;
          rec_hash: string | null;
          signature_transforms: unknown | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          xml_version: string;
          xml_parsing_timestamp?: string;
          usuario_id?: string | null;
          empresa_id: string;
          xml_id: string;
          tp_amb?: number | null;
          proc_emi?: number | null;
          ver_proc?: string | null;
          emp_tp_insc?: number | null;
          emp_nr_insc?: string | null;
          rub_operation_type?: string | null;
          rub_cod_rubr?: string | null;
          rub_ide_tab_rubr?: string | null;
          rub_ini_valid?: string | null;
          rub_fim_valid?: string | null;
          rub_dsc_rubr?: string | null;
          rub_nat_rubr?: number | null;
          rub_tp_rubr?: number | null;
          rub_cod_inc_cp?: number | null;
          rub_cod_inc_irrf?: number | null;
          rub_cod_inc_fgts?: number | null;
          rub_cod_inc_sind?: number | null;
          rec_tp_amb?: number | null;
          rec_dh_recepcao?: string | null;
          rec_versao_app_recepcao?: string | null;
          rec_protocolo_envio?: string | null;
          rec_cd_resposta?: number | null;
          rec_desc_resposta?: string | null;
          rec_dh_processamento?: string | null;
          rec_nr_recibo?: string | null;
          rec_hash?: string | null;
          signature_transforms?: unknown | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          xml_version?: string;
          xml_parsing_timestamp?: string;
          usuario_id?: string | null;
          empresa_id?: string;
          xml_id?: string;
          tp_amb?: number | null;
          proc_emi?: number | null;
          ver_proc?: string | null;
          emp_tp_insc?: number | null;
          emp_nr_insc?: string | null;
          rub_operation_type?: string | null;
          rub_cod_rubr?: string | null;
          rub_ide_tab_rubr?: string | null;
          rub_ini_valid?: string | null;
          rub_fim_valid?: string | null;
          rub_dsc_rubr?: string | null;
          rub_nat_rubr?: number | null;
          rub_tp_rubr?: number | null;
          rub_cod_inc_cp?: number | null;
          rub_cod_inc_irrf?: number | null;
          rub_cod_inc_fgts?: number | null;
          rub_cod_inc_sind?: number | null;
          rec_tp_amb?: number | null;
          rec_dh_recepcao?: string | null;
          rec_versao_app_recepcao?: string | null;
          rec_protocolo_envio?: string | null;
          rec_cd_resposta?: number | null;
          rec_desc_resposta?: string | null;
          rec_dh_processamento?: string | null;
          rec_nr_recibo?: string | null;
          rec_hash?: string | null;
          signature_transforms?: unknown | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      xml_router_config: {
        Row: {
          id: string;
          tag_xml: string;
          codigo_evento: string;
          tabela_destino: string;
          ativo: boolean;
          ordem_prioridade: number;
          descricao: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tag_xml: string;
          codigo_evento: string;
          tabela_destino: string;
          ativo?: boolean;
          ordem_prioridade?: number;
          descricao?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tag_xml?: string;
          codigo_evento?: string;
          tabela_destino?: string;
          ativo?: boolean;
          ordem_prioridade?: number;
          descricao?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

export type Empresa = Database['public']['Tables']['empresas']['Row'];
export type Rubrica = Database['public']['Tables']['rubricas']['Row'];
export type Colaborador = Database['public']['Tables']['colaboradores']['Row'];
export type Importacao = Database['public']['Tables']['importacoes']['Row'];
export type Remuneracao = Database['public']['Tables']['remuneracoes']['Row'];
export type ItemRemuneracao = Database['public']['Tables']['itens_remuneracao']['Row'];
export type Divergencia = Database['public']['Tables']['divergencias']['Row'];
export type Apuracao = Database['public']['Tables']['apuracoes']['Row'];
export type BaseConhecimentoRubrica = Database['public']['Tables']['base_conhecimento_rubricas']['Row'];
export type EventoS1070 = Database['public']['Tables']['evt_s1070']['Row'];
export type DadosEmpresaAuditoria = Database['public']['Tables']['dados_empresa_auditoria']['Row'];
export type RubricaProcessoVinculo = Database['public']['Tables']['rubrica_processo_vinculo']['Row'];
export type EntendimentoTributacao = Database['public']['Tables']['entendimentos_tributacao']['Row'];
export type EventoS1000 = Database['public']['Tables']['evt_s1000']['Row'];
export type EventoS1010 = Database['public']['Tables']['evt_s1010']['Row'];
export type XmlRouterConfig = Database['public']['Tables']['xml_router_config']['Row'];
